export interface ModelInfo {
  name: string        // Ollama pull name / catalog identifier
  webllmId?: string   // @mlc-ai/web-llm model ID (browser-native, no install needed)
  label: string
  vramGB: number      // VRAM needed at Q4 quantization
  sizeGB: number      // Download size in GB
  toolCalling: boolean
  reasoning: boolean
  description: string
}

export const MODEL_CATALOG: ModelInfo[] = [
  {
    name: 'llama3.2:1b',
    webllmId: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
    label: 'Llama 3.2 1B',
    vramGB: 1.3,
    sizeGB: 0.8,
    toolCalling: true,
    reasoning: false,
    description: 'Runs on anything · good for very limited hardware',
  },
  {
    name: 'gemma2:2b',
    webllmId: 'gemma-2-2b-it-q4f16_1-MLC',
    label: 'Gemma 2 2B',
    vramGB: 1.6,
    sizeGB: 1.5,
    toolCalling: false,
    reasoning: false,
    description: "Google 2B · surprisingly smart for its size",
  },
  {
    name: 'llama3.2:3b',
    webllmId: 'Llama-3.2-3B-Instruct-q4f16_1-MLC',
    label: 'Llama 3.2 3B',
    vramGB: 2.0,
    sizeGB: 1.9,
    toolCalling: true,
    reasoning: false,
    description: 'Meta 3B with tool calling · fast on any GPU',
  },
  {
    name: 'qwen2.5:3b',
    webllmId: 'Qwen2.5-3B-Instruct-q4f16_1-MLC',
    label: 'Qwen 2.5 3B',
    vramGB: 2.0,
    sizeGB: 2.0,
    toolCalling: true,
    reasoning: false,
    description: 'Alibaba 3B · fast, good instruction following',
  },
  {
    name: 'deepseek-r1:7b',
    webllmId: 'DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC',
    label: 'DeepSeek R1 7B',
    vramGB: 4.7,
    sizeGB: 4.5,
    toolCalling: true,
    reasoning: true,
    description: 'Distilled from 671B R1 · best reasoning at 7B size',
  },
  {
    name: 'qwen2.5:7b',
    webllmId: 'Qwen2.5-7B-Instruct-q4f16_1-MLC',
    label: 'Qwen 2.5 7B',
    vramGB: 4.7,
    sizeGB: 4.7,
    toolCalling: true,
    reasoning: false,
    description: 'Best 7B for tool calling + strong instruction following',
  },
  {
    name: 'llama3.1:8b',
    webllmId: 'Llama-3.1-8B-Instruct-q4f32_1-MLC',
    label: 'Llama 3.1 8B',
    vramGB: 4.9,
    sizeGB: 5.0,
    toolCalling: true,
    reasoning: false,
    description: "Meta flagship 8B · solid tool use support",
  },
  {
    name: 'mistral-nemo',
    label: 'Mistral Nemo 12B',
    vramGB: 7.1,
    sizeGB: 7.1,
    toolCalling: true,
    reasoning: false,
    description: '12B · excellent multilingual + accurate tool calling',
  },
  {
    name: 'deepseek-r1:14b',
    webllmId: 'DeepSeek-R1-Distill-Qwen-14B-q4f16_1-MLC',
    label: 'DeepSeek R1 14B',
    vramGB: 9.0,
    sizeGB: 9.0,
    toolCalling: true,
    reasoning: true,
    description: 'R1 distill 14B · deep step-by-step reasoning chains',
  },
  {
    name: 'phi4',
    webllmId: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
    label: 'Phi-4 14B',
    vramGB: 9.1,
    sizeGB: 9.1,
    toolCalling: true,
    reasoning: false,
    description: 'Microsoft 14B · beats many 30B+ models on benchmarks',
  },
  {
    name: 'qwen2.5:14b',
    webllmId: 'Qwen2.5-14B-Instruct-q4f16_1-MLC',
    label: 'Qwen 2.5 14B',
    vramGB: 9.0,
    sizeGB: 9.0,
    toolCalling: true,
    reasoning: false,
    description: 'Strong 14B · excellent code + tool use accuracy',
  },
  {
    name: 'deepseek-r1:32b',
    label: 'DeepSeek R1 32B',
    vramGB: 19.8,
    sizeGB: 19.8,
    toolCalling: true,
    reasoning: true,
    description: 'Near-GPT-4 quality · R1 32B distill · needs 24GB VRAM',
  },
  {
    name: 'llama3.3:70b',
    label: 'Llama 3.3 70B',
    vramGB: 43,
    sizeGB: 43,
    toolCalling: true,
    reasoning: false,
    description: "Meta's most capable open model · needs high-end GPU",
  },
  {
    name: 'deepseek-r1:70b',
    label: 'DeepSeek R1 70B',
    vramGB: 43,
    sizeGB: 43,
    toolCalling: true,
    reasoning: true,
    description: 'Strongest open reasoning model · matches o1 on benchmarks',
  },
]
